### ISSUE TITLE
[기능] article과 user m:n 맵핑

### ISSUE THREAD

**Issue by sangho0n** [softeerbootcamp/Team3#39]
🥞 요약
---
article과 user 테이블 간 다대다 맵핑 관계에 따른 코드 리팩토링

📌 해야할 일
---
- [x] user_article_relationship 테이블 생성
- [x] 새롭게 생성된 테이블 dao 작성
- [ ] article vo의 int hostId -> User host
- [ ] article dto의 int hostId -> User host
- [ ] 바뀐 변수명/변수타입에 따라 article dao 리팩토링

**Comment by yunjaeGong** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GatherGo-63db861d9013610026b9150e/issues/softeerbootcamp/Team3/39?planning-poker) with Zenhub @sangho0n
